color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.8109149935189635
  lightness: 0.8156924450304359
  saturation: 0.09732232918031514
  rhythmicContrast: 0.9140569150913507
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Jacob Sansbury
layout_spectrum: 0.5577488411217928
typography_spectrum: 0.19178682356141508
content: []
github: true
url: 'https://jsansbury.com'
author:
  name: Jacob Sansbury
  email: sansburyjacob@gmail.com
title: Jacob Sansbury
description: ''
